/**
 * 圣遗物主词条表
 */
export const ArtifactParamTypes = [
    'HP',
    'ATK',
    'DEF',
    'Elemental Mastery',
    'Energy Recharge',
    'Healing Bonus',
    'Physical DMG Bonus',
    'Anemo DMG Bonus',
    'Geo DMG Bonus',
    'Electro DMG Bonus',
    'Hydro DMG Bonus',
    'Pyro DMG Bonus',
    'Cryo DMG Bonus',
]
/**
 * 圣遗物副词条表
 */
export const ArtifactSubParamTypes = [
    'HP',
    'ATK',
    'DEF',
    'ElementaL Mastery',
    'Energy Recharge',
    'CRIT Rate',
    'CRIT DMG',
]
/**
 * 圣遗物名表
 */
export const ArtifactNames = [
    'Adventurer%20Bandana',
    'Adventurer%20Flower',
    'Adventurer%20Golden%20Goblet',
    'Adventurer%20Pocket%20Watch',
    'Adventurer%20Tail%20Feather',
    'Bard%20Arrow%20Feather',
    'Berserker%20Battle%20Mask',
    'Berserker%20Bone%20Goblet',
    'Berserker%20Indigo%20Feather',
    'Berserker%20Rose',
    'Berserker%20Timepiece',
    'Bloodstained%20Black%20Plume',
    'Bloodstained%20Chevalier%20Goblet',
    'Bloodstained%20Final%20Hour',
    'Bloodstained%20Flower%20of%20Iron',
    'Bloodstained%20Iron%20Mask',
    'Broken%20Rime%20Echo',
    'Ceremonial%20War-Plume',
    'Concert%20Final%20Hour',
    'Conductor%20Top%20Hat',
    'Copper%20Compass',
    'Crown%20of%20Parting',
    'Crown%20of%20the%20Brave',
    'Exile%20Circlet',
    'Exile%20Feather',
    'Exile%20Flower',
    'Exile%20Goblet',
    'Exile%20Pocket%20Watch',
    'Feather%20of%20Homecoming',
    'Feather%20of%20Jagged%20Peaks',
    'Flower%20of%20Accolades',
    'Flower%20of%20Creviced%20Cliff',
    'Fortitude%20of%20the%20Brave',
    'Frost-Weaved%20Dignity',
    'Frozen%20Homeland%20Demise',
    'Gambler%20Brooch',
    'Gambler%20Dice%20Cup',
    'Gambler%20Earrings',
    'Gambler%20Feather%20Accessory',
    'Gambler%20Pocket%20Watch',
    'General%20Ancient%20Helm',
    'Gilded%20Corsage',
    'Gladiator%20Destiny',
    'Gladiator%20Intoxication',
    'Gladiator%20Longing',
    'Gladiator%20Nostalgia',
    'Gladiator%20Triumphus',
    'Goblet%20of%20Chiseled%20Crag',
    'Goblet%20of%20the%20Sojourner',
    'Goblet%20of%20Thundering%20Deep',
    'Guardian%20Band',
    'Guardian%20Clock',
    'Guardian%20Flower',
    'Guardian%20Sigil',
    'Guardian%20Vessel',
    'Gust%20of%20Nostalgia',
    'Heart%20of%20Comradeship',
    'Hour%20of%20Soothing%20Thunder',
    'Hourglass%20of%20Thunder',
    'Icebreaker%20Resolve',
    'In%20Remembrance%20of%20Viridescent%20Fields',
    'Instructor%20Brooch',
    'Instructor%20Cap',
    'Instructor%20Feather%20Accessory',
    'Instructor%20Pocket%20Watch',
    'Instructor%20Tea%20Cup',
    'Lavawalker%20Epiphany',
    'Lavawalker%20Resolution',
    'Lavawalker%20Salvation',
    'Lavawalker%20Torment',
    'Lavawalker%20Wisdom',
    'Lucky%20Dog%20Clover',
    'Lucky%20Dog%20Eagle%20Feather',
    'Lucky%20Dog%20Goblet',
    'Lucky%20Dog%20Hourglass',
    'Lucky%20Dog%20Silver%20Circlet',
    'Maiden%20Distant%20Love',
    'Maiden%20Fading%20Beauty',
    'Maiden%20Fleeting%20Leisure',
    'Maiden%20Heart-stricken%20Infatuation',
    'Maiden%20Passing%20Youth',
    'Martial%20Artist%20Bandana',
    'Martial%20Artist%20Feather%20Accessory',
    'Martial%20Artist%20Red%20Flower',
    'Martial%20Artist%20Water%20Hourglass',
    'Martial%20Artist%20Wine%20Cup',
    'Mask%20of%20Solitude%20Basalt',
    'Medal%20of%20the%20Brave',
    'Mocking%20Mask',
    'Moment%20of%20Cessation',
    'Noble%20Pledging%20Vessel',
    'Omen%20of%20Thunderstorm',
    'Orichalceous%20Time-Dial',
    'Outset%20of%20the%20Brave',
    'Prospect%20of%20the%20Brave',
    'Royal%20Flora',
    'Royal%20Masque',
    'Royal%20Plume',
    'Royal%20Pocket%20Watch',
    'Royal%20Silver%20Urn',
    'Scholar%20Bookmark',
    'Scholar%20Clock',
    'Scholar%20Ink%20Cup',
    'Scholar%20Lens',
    'Scholar%20Quill%20Pen',
    'Snowswept%20Memory',
    'Stainless%20Bloom',
    'Summer%20Night%20Bloom',
    'Summer%20Night%20Finale',
    'Summer%20Night%20Mask',
    'Summer%20Night%20Moment',
    'Summer%20Night%20Waterballoon',
    'Sundial%20of%20Enduring%20Jade',
    'Sundial%20of%20the%20Sojourner',
    'Surpassing%20Cup',
    'Survivor%20of%20Catastrophe',
    'Thunder%20Summoner%20Crown',
    'Thunderbird%20Mercy',
    'Thundersoother%20Diadem',
    'Thundersoother%20Goblet',
    'Thundersoother%20Heart',
    'Thundersoother%20Plume',
    'Tiara%20of%20Flame',
    'Tiara%20of%20Frost',
    'Tiara%20of%20Thunder',
    'Tiara%20of%20Torrents',
    'Tiny%20Miracle%20Earrings',
    'Tiny%20Miracle%20Feather',
    'Tiny%20Miracle%20Flower',
    'Tiny%20Miracle%20Goblet',
    'Tiny%20Miracle%20Hourglass',
    'Traveling%20Doctor%20Handkerchief',
    'Traveling%20Doctor%20Medicine%20Pot',
    'Traveling%20Doctor%20Owl%20Feather',
    'Traveling%20Doctor%20Pocket%20Watch',
    'Traveling%20Doctor%20Silver%20Lotus',
    'Troupe%20Dawnlight',
    'Viridescent%20Arrow%20Feather',
    'Viridescent%20Venerer%20Determination',
    'Viridescent%20Venerer%20Diadem',
    'Viridescent%20Venerer%20Vessel',
    'Wanderer%20String%20Kettle',
    'Wine-Stained%20Tricorne',
    'Wise%20Doctor%20Pinion',
    'Witch%20End%20Time',
    'Witch%20Ever-Burning%20Plume',
    'Witch%20Flower%20of%20Blaze',
    'Witch%20Heart%20Flames',
    'Witch%20Scorching%20Hat',
    
    
    
]
/**
 *  圣遗物使用者表
 */
export const ArtifactUsers = [
    '空已装备',
    '荧已装备',
    '安柏已装备',
    '凯亚已装备',
    '丽莎已装备',
    '琴已装备',
    '可莉已装备',
    '诺艾尔已装备',
    '芭芭拉已装备',
    '温迪已装备',
    '雷泽已装备',
    '迪卢克已装备',
    '班尼特已装备',
    '菲谢尔已装备',
    '北斗已装备',
    '凝光已装备',
    '香菱已装备',
    '行秋已装备',
    '重云已装备',
    '砂糖已装备',
    '莫娜已装备',
    '刻晴已装备',
    '七七已装备',
    '达达利亚已装备',
    '迪奥娜已装备',
    '钟离已装备',
    '辛焱已装备',
    '阿贝多已装备',
    '甘雨已装备',
    '魈已装备',
    '胡桃已装备',
    '罗莎莉亚已装备',
]
