/**
 * 圣遗物主词条表
 */
export const ArtifactParamTypes = [
    'HP',
    'ATK',
    'DEF',
    'Elemental Mastery',
    'Energy Recharge',
    'Healing Bonus',
    'Physical DMG Bonus',
    'Anemo DMG Bonus',
    'Geo DMG Bonus',
    'Electro DMG Bonus',
    'Hydro DMG Bonus',
    'Pyro DMG Bonus',
    'Cryo DMG Bonus',
]
/**
 * 圣遗物副词条表
 */
export const ArtifactSubParamTypes = [
    'HP',
    'ATK',
    'DEF',
    'ElementaL Mastery',
    'Energy Recharge',
    'CRIT Rate',
    'CRIT DMG',
]
/**
 * 圣遗物名表
 */
export const ArtifactNames = [
    'Adventurer_Bandana',
'Adventurer_Flower',
'Adventurer_Golden_Goblet',
'Adventurer_Pocket_Watch',
'Adventurer_Tail_Feather',
'Bard_Arrow_Feather',
'Berserker_Battle_Mask',
'Berserker_Bone_Goblet',
'Berserker_Indigo_Feather',
'Berserker_Rose',
'Berserker_Timepiece',
'Bloodstained_Black_Plume',
'Bloodstained_Chevalier_Goblet',
'Bloodstained_Final_Hour',
'Bloodstained_Flower_of_Iron',
'Bloodstained_Iron_Mask',
'Broken_Rime_Echo',
'Ceremonial_War-Plume',
'Concert_Final_Hour',
'Conductor_Top_Hat',
'Copper_Compass',
'Crown_of_Parting',
'Crown_of_the_Brave',
'Exile_Circlet',
'Exile_Feather',
'Exile_Flower',
'Exile_Goblet',
'Exile_Pocket_Watch',
'Feather_of_Homecoming',
'Feather_of_Jagged_Peaks',
'Flower_of_Accolades',
'Flower_of_Creviced_Cliff',
'Fortitude_of_the_Brave',
'Frost-Weaved_Dignity',
'Frozen_Homeland_Demise',
'Gambler_Brooch',
'Gambler_Dice_Cup',
'Gambler_Earrings',
'Gambler_Feather_Accessory',
'Gambler_Pocket_Watch',
'General_Ancient_Helm',
'Gilded_Corsage',
'Gladiator_Destiny',
'Gladiator_Intoxication',
'Gladiator_Longing',
'Gladiator_Nostalgia',
'Gladiator_Triumphus',
'Goblet_of_Chiseled_Crag',
'Goblet_of_the_Sojourner',
'Goblet_of_Thundering_Deep',
'Guardian_Band',
'Guardian_Clock',
'Guardian_Flower',
'Guardian_Sigil',
'Guardian_Vessel',
'Gust_of_Nostalgia',
'Heart_of_Comradeship',
'Hour_of_Soothing_Thunder',
'Hourglass_of_Thunder',
'Icebreaker_Resolve',
'In_Remembrance_of_Viridescent_Fields',
'Instructor_Brooch',
'Instructor_Cap',
'Instructor_Feather_Accessory',
'Instructor_Pocket_Watch',
'Instructor_Tea_Cup',
'Lavawalker_Epiphany',
'Lavawalker_Resolution',
'Lavawalker_Salvation',
'Lavawalker_Torment',
'Lavawalker_Wisdom',
'Lucky_Dog_Clover',
'Lucky_Dog_Eagle_Feather',
'Lucky_Dog_Goblet',
'Lucky_Dog_Hourglass',
'Lucky_Dog_Silver_Circlet',
'Maiden_Distant_Love',
'Maiden_Fading_Beauty',
'Maiden_Fleeting_Leisure',
'Maiden_Heart-stricken_Infatuation',
'Maiden_Passing_Youth',
'Martial_Artist_Bandana',
'Martial_Artist_Feather_Accessory',
'Martial_Artist_Red_Flower',
'Martial_Artist_Water_Hourglass',
'Martial_Artist_Wine_Cup',
'Mask_of_Solitude_Basalt',
'Medal_of_the_Brave',
'Mocking_Mask',
'Moment_of_Cessation',
'Noble_Pledging_Vessel',
'Omen_of_Thunderstorm',
'Orichalceous_Time-Dial',
'Outset_of_the_Brave',
'Prospect_of_the_Brave',
'Royal_Flora',
'Royal_Masque',
'Royal_Plume',
'Royal_Pocket_Watch',
'Royal_Silver_Urn',
'Scholar_Bookmark',
'Scholar_Clock',
'Scholar_Ink_Cup',
'Scholar_Lens',
'Scholar_Quill_Pen',
'Snowswept_Memory',
'Stainless_Bloom',
'Summer_Night_Bloom',
'Summer_Night_Finale',
'Summer_Night_Mask',
'Summer_Night_Moment',
'Summer_Night_Waterballoon',
'Sundial_of_Enduring_Jade',
'Sundial_of_the_Sojourner',
'Surpassing_Cup',
'Survivor_of_Catastrophe',
'Thunder_Summoner_Crown',
'Thunderbird_Mercy',
'Thundersoother_Diadem',
'Thundersoother_Goblet',
'Thundersoother_Heart',
'Thundersoother_Plume',
'Tiara_of_Flame',
'Tiara_of_Frost',
'Tiara_of_Thunder',
'Tiara_of_Torrents',
'Tiny_Miracle_Earrings',
'Tiny_Miracle_Feather',
'Tiny_Miracle_Flower',
'Tiny_Miracle_Goblet',
'Tiny_Miracle_Hourglass',
'Traveling_Doctor_Handkerchief',
'Traveling_Doctor_Medicine_Pot',
'Traveling_Doctor_Owl_Feather',
'Traveling_Doctor_Pocket_Watch',
'Traveling_Doctor_Silver_Lotus',
'Troupe_Dawnlight',
'Viridescent_Arrow_Feather',
'Viridescent_Venerer_Determination',
'Viridescent_Venerer_Diadem',
'Viridescent_Venerer_Vessel',
'Wanderer_String_Kettle',
'Wine-Stained_Tricorne',
'Wise_Doctor_Pinion',
'Witch_End_Time',
'Witch_Ever-Burning_Plume',
'Witch_Flower_of_Blaze',
'Witch_Heart_Flames',
'Witch_Scorching_Hat',
]
/**
 *  圣遗物使用者表
 */
export const ArtifactUsers = [
    '空已装备',
    '荧已装备',
    '安柏已装备',
    '凯亚已装备',
    '丽莎已装备',
    '琴已装备',
    '可莉已装备',
    '诺艾尔已装备',
    '芭芭拉已装备',
    '温迪已装备',
    '雷泽已装备',
    '迪卢克已装备',
    '班尼特已装备',
    '菲谢尔已装备',
    '北斗已装备',
    '凝光已装备',
    '香菱已装备',
    '行秋已装备',
    '重云已装备',
    '砂糖已装备',
    '莫娜已装备',
    '刻晴已装备',
    '七七已装备',
    '达达利亚已装备',
    '迪奥娜已装备',
    '钟离已装备',
    '辛焱已装备',
    '阿贝多已装备',
    '甘雨已装备',
    '魈已装备',
    '胡桃已装备',
    '罗莎莉亚已装备',
]
