/**
 * 圣遗物主词条表
 */
export const ArtifactParamTypes = [
    'HP',
    'ATK',
    'DEF',
    'Elemental Mastery',
    'Energy Recharge',
    'Healing Bonus',
    'Physical DMG Bonus',
    'Anemo DMG Bonus',
    'Geo DMG Bonus',
    'Electro DMG Bonus',
    'Hydro DMG Bonus',
    'Pyro DMG Bonus',
    'Cryo DMG Bonus',
]
/**
 * 圣遗物副词条表
 */
export const ArtifactSubParamTypes = [
    'HP',
    'ATK',
    'DEF',
    'ElementaL Mastery',
    'Energy Recharge',
    'CRIT Rate',
    'CRIT DMG',
]
/**
 * 圣遗物名表
 */
export const ArtifactNames = [
    'Adventurer Bandana',
'Adventurer Flower',
'Adventurer Golden Goblet',
'Adventurer Pocket Watch',
'Adventurer Tail Feather',
'Bard Arrow Feather',
'Berserker Battle Mask',
'Berserker Bone Goblet',
'Berserker Indigo Feather',
'Berserker Rose',
'Berserker Timepiece',
'Bloodstained Black Plume',
'Bloodstained Chevalier Goblet',
'Bloodstained Final Hour',
'Bloodstained Flower of Iron',
'Bloodstained Iron Mask',
'Broken Rime Echo',
'Ceremonial War-Plume',
'Concert Final Hour',
'Conductor Top Hat',
'Copper Compass',
'Crown of Parting',
'Crown of the Brave',
'Exile Circlet',
'Exile Feather',
'Exile Flower',
'Exile Goblet',
'Exile Pocket Watch',
'Feather of Homecoming',
'Feather of Jagged Peaks',
'Flower of Accolades',
'Flower of Creviced Cliff',
'Fortitude of the Brave',
'Frost-Weaved Dignity',
'Frozen Homeland Demise',
'Gambler Brooch',
'Gambler Dice Cup',
'Gambler Earrings',
'Gambler Feather Accessory',
'Gambler Pocket Watch',
'General Ancient Helm',
'Gilded Corsage',
'Gladiator Destiny',
'Gladiator Intoxication',
'Gladiator Longing',
'Gladiator Nostalgia',
'Gladiator Triumphus',
'Goblet of Chiseled Crag',
'Goblet of the Sojourner',
'Goblet of Thundering Deep',
'Guardian Band',
'Guardian Clock',
'Guardian Flower',
'Guardian Sigil',
'Guardian Vessel',
'Gust of Nostalgia',
'Heart of Comradeship',
'Hour of Soothing Thunder',
'Hourglass of Thunder',
'Icebreaker Resolve',
'In Remembrance of Viridescent Fields',
'Instructor Brooch',
'Instructor Cap',
'Instructor Feather Accessory',
'Instructor Pocket Watch',
'Instructor Tea Cup',
'Lavawalker Epiphany',
'Lavawalker Resolution',
'Lavawalker Salvation',
'Lavawalker Torment',
'Lavawalker Wisdom',
'Lucky Dog Clover',
'Lucky Dog Eagle Feather',
'Lucky Dog Goblet',
'Lucky Dog Hourglass',
'Lucky Dog Silver Circlet',
'Maiden Distant Love',
'Maiden Fading Beauty',
'Maiden Fleeting Leisure',
'Maiden Heart-stricken Infatuation',
'Maiden Passing Youth',
'Martial Artist Bandana',
'Martial Artist Feather Accessory',
'Martial Artist Red Flower',
'Martial Artist Water Hourglass',
'Martial Artist Wine Cup',
'Mask of Solitude Basalt',
'Medal of the Brave',
'Mocking Mask',
'Moment of Cessation',
'Noble Pledging Vessel',
'Omen of Thunderstorm',
'Orichalceous Time-Dial',
'Outset of the Brave',
'Prospect of the Brave',
'Royal Flora',
'Royal Masque',
'Royal Plume',
'Royal Pocket Watch',
'Royal Silver Urn',
'Scholar Bookmark',
'Scholar Clock',
'Scholar Ink Cup',
'Scholar Lens',
'Scholar Quill Pen',
'Snowswept Memory',
'Stainless Bloom',
'Summer Night Bloom',
'Summer Night Finale',
'Summer Night Mask',
'Summer Night Moment',
'Summer Night Waterballoon',
'Sundial of Enduring Jade',
'Sundial of the Sojourner',
'Surpassing Cup',
'Survivor of Catastrophe',
'Thunder Summoner Crown',
'Thunderbird Mercy',
'Thundersoother Diadem',
'Thundersoother Goblet',
'Thundersoother Heart',
'Thundersoother Plume',
'Tiara of Flame',
'Tiara of Frost',
'Tiara of Thunder',
'Tiara of Torrents',
'Tiny Miracle Earrings',
'Tiny Miracle Feather',
'Tiny Miracle Flower',
'Tiny Miracle Goblet',
'Tiny Miracle Hourglass',
'Traveling Doctor Handkerchief',
'Traveling Doctor Medicine Pot',
'Traveling Doctor Owl Feather',
'Traveling Doctor Pocket Watch',
'Traveling Doctor Silver Lotus',
'Troupe Dawnlight',
'Viridescent Arrow Feather',
'Viridescent Venerer Determination',
'Viridescent Venerer Diadem',
'Viridescent Venerer Vessel',
'Wanderer String Kettle',
'Wine-Stained Tricorne',
'Wise Doctor Pinion',
'Witch End Time',
'Witch Ever-Burning Plume',
'Witch Flower of Blaze',
'Witch Heart Flames',
'Witch Scorching Hat',
]
/**
 *  圣遗物使用者表
 */
export const ArtifactUsers = [
    '空已装备',
    '荧已装备',
    '安柏已装备',
    '凯亚已装备',
    '丽莎已装备',
    '琴已装备',
    '可莉已装备',
    '诺艾尔已装备',
    '芭芭拉已装备',
    '温迪已装备',
    '雷泽已装备',
    '迪卢克已装备',
    '班尼特已装备',
    '菲谢尔已装备',
    '北斗已装备',
    '凝光已装备',
    '香菱已装备',
    '行秋已装备',
    '重云已装备',
    '砂糖已装备',
    '莫娜已装备',
    '刻晴已装备',
    '七七已装备',
    '达达利亚已装备',
    '迪奥娜已装备',
    '钟离已装备',
    '辛焱已装备',
    '阿贝多已装备',
    '甘雨已装备',
    '魈已装备',
    '胡桃已装备',
    '罗莎莉亚已装备',
]
